version: '3.4'

services:

  serviceone:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  #service-two:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "80"

  blazor-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

